spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.kyuleelim.admincore
  configuration:
    map-underscore-to-camel-case: true

thymeleaf:
  cache: false

logging:
  level:
    com.kyuleelim.admincore: DEBUG
    org.mybatis: DEBUG
    jdbc.sqlonly: DEBUG
