# DB Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

# MyBatis Setting
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.kyuleelim.admincore
  configuration:
    map-underscore-to-camel-case: true

thymeleaf:
  cache: false

logging:
  level:
    com.kyuleelim.admincore: DEBUG
    org.mybatis: DEBUG
    jdbc.sqlonly: DEBUG
