spring:
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api

datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.kyuleelim.admincore.domain
  configuration:
    map-underscore-to-camel-case: true

# Swagger Setting
springdoc:
    override-with-generic-response: true
    default-consumes-media-type: application/json # 소비 미디어 타입
    default-produces-media-type: application/json # 생산 미디어 타입
    servers:
      - url: http://localhost:8080
        description: 로컬 개발 서버

jwt:
  #  chatserversecretaccesstokenchatserversecretaccesstokenchatserversecretaccesstoken
  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 # 3000분