spring:
  datasource:
    url: jdbc:postgresql://ep-jolly-water-ae8gptqy-pooler.c-2.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_g1ZK8nXOhEao&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_g1ZK8nXOhEao
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kyuleelim.admincore
  configuration:
    map-underscore-to-camel-case: true

# Swagger Setting
springdoc:
    override-with-generic-response: true
    default-consumes-media-type: application/json # 소비 미디어 타입
    default-produces-media-type: application/json # 생산 미디어 타입
    servers:
      - url: http://localhost:8080/api
        description: 로컬 개발 서버
