DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NM VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100),
    USE_YN CHAR(1) DEFAULT 'Y',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);